services:
  nextjs1:
    build: .
    ports:
      - "3001:3000"
    environment:
      - REDIS_URL=redis-stack
    depends_on:
      - redis-stack
    networks:
      - webnet

  nextjs2:
    build: .
    ports:
      - "3002:3000"
    environment:
      - REDIS_URL=redis-stack
    depends_on:
      - redis-stack
    networks:
      - webnet

  redis-stack:
    image: redis/redis-stack:latest
    container_name: cache-handler-redis
    ports:
      - "6379:6379"
      - "8001:8001"
    volumes:
      - redis-data:/data
    networks:
      - webnet

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "3380:3380"
    depends_on:
      - nextjs1
      - nextjs2
    networks:
      - webnet

volumes:
  redis-data:

networks:
  webnet: